FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY api-gateway/.mvn/ .mvn
COPY api-gateway/mvnw api-gateway/pom.xml ./
RUN ./mvnw dependency:go-offline
COPY api-gateway/src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "/app/app.jar"]