FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY user-service/.mvn/ .mvn
COPY user-service/mvnw user-service/pom.xml ./
RUN ./mvnw dependency:go-offline
COPY user-service/src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]